x <- read.csv("household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactors=FALSE)
x <- subset(x,Date %in% c("1/2/2007","2/2/2007"))
x$DateTime <- strptime(paste(x$Date,x$Time),"%d/%m/%Y %T")

png(file = "plot3.png", width = 480, height = 480)
with(x,plot(DateTime, Sub_metering_1, type = "n", xlab="", ylab="Energy sub metering"))
with(x,lines(DateTime, Sub_metering_1, col="black", type="l"))
with(x,lines(DateTime, Sub_metering_2, col="red", type="l"))
with(x,lines(DateTime, Sub_metering_3, col="blue", type="l"))
legend("topright",col=c("black", "red", "blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=1 )     
dev.off()